name: camera_example
description: Demonstrates how to use the camera plugin.

dependencies:
  flutter_better_camera:
    path: ../
  path_provider: ^2.0.1
  flutter:
    sdk: flutter
  video_player: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.22.0 <3.0.0"
